id: I56A00ECC
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-13T19:30:40+00:00'
last_modified: '2022-06-10T04:41:08.954959+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG21959
  title: ས་སྐྱའི་ལམ་འབྲས་བླ་བརྒྱུད་ཀྱི་རྣམ་ཐར།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    EB79:
      image_group_id: I1KG21983
      title: Volume 1 of sa skya pa lam 'bras bla brgyud kyi rnam thar/
      total_pages: 662
      order: 1
      base_file: EB79.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
